### ISSUE TITLE
Does not understand tilde (~) in path

### ISSUE THREAD

**Issue by hanxue** [stevenjack/cig#31] opened 2015-06-19 03:34 UTC
This works

`/Users/hanxue/Code`

This does not

`~/Code`

Will cause error

```
Checking 'personal' (~/Github) repos...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x4e364]

goroutine 1 [running]:
github.com/stevenjack/cig/app.func·001(0x20833c900, 0x8, 0x0, 0x0, 0x2208345a08, 0x20836a870, 0x0, 0x0)
    /private/tmp/cig20150617-87013-6afwi4/cig-0.1.3/src/github.com/stevenjack/cig/app/app.go:23 +0x94
path/filepath.Walk(0x20833c900, 0x8, 0x20835db18, 0x0, 0x0)
    /usr/local/Cellar/go/1.4.2/libexec/src/path/filepath/path.go:392 +0xb6
github.com/stevenjack/cig/app.Handle(0x20836a6f0, 0x2e4b18, 0x0, 0x2e4b18, 0x0, 0x20839c060)
    /private/tmp/cig20150617-87013-6afwi4/cig-0.1.3/src/github.com/stevenjack/cig/app/app.go:30 +0x40f
main.func·001(0x2083980e0)
    /private/tmp/cig20150617-87013-6afwi4/cig-0.1.3/cig.go:29 +0x1c7
github.com/stevenjack/cig/Godeps/_workspace/src/github.com/codegangsta/cli.(*App).Run(0x2083ac000, 0x20833c000, 0x1, 0x1, 0x0, 0x0)
    /private/tmp/cig20150617-87013-6afwi4/cig-0.1.3/src/github.com/stevenjack/cig/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:182 +0xe5c
main.main()
    /private/tmp/cig20150617-87013-6afwi4/cig-0.1.3/cig.go:32 +0x12c

goroutine 5 [chan receive]:
github.com/stevenjack/cig/output.Wait(0x20839c060)
    /private/tmp/cig20150617-87013-6afwi4/cig-0.1.3/src/github.com/stevenjack/cig/output/output.go:46 +0x7c
created by main.main
    /private/tmp/cig20150617-87013-6afwi4/cig-0.1.3/cig.go:16 +0x80
```
## Suggestion
1. User friendly error message when path not found
2. Should process bash shortcuts and environment variables such as `~` and `$HOME`

**Comment by stevenjack** [comment] 2015-06-19 06:48
Duplicate of https://github.com/stevenjack/cig/issues/29

**Closed as completed** 2015-07-19 12:45 UTC
Labels: Bug, Duplicate
